version: '3'

volumes:
  keycloak_data:
    driver: local
  database_data:
    driver: local

networks:
  keycloak_database_network:
    driver: bridge

services:
  postgres:
    image: postgres:13
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: support-pipe
    ports:
      - 5433:5432
  keycloak_database:
    image: postgres:13
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - keycloak_database_network
  keycloak:
    depends_on:
      - keycloak_database
    image: jboss/keycloak:13.0.1
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: keycloak_database
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_IMPORT: /tmp/support-pipe-realm.json
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      # JDBC_PARAMS: "ssl=true"
    volumes:
      - ./support-pipe-keycloak/support-pipe-realm.json:/tmp/support-pipe-realm.json
    ports:
      - 8080:8080
    networks:
      - keycloak_database_network
  artemis:
    image: vromero/activemq-artemis:2.9.0-alpine
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    environment:
      ARTEMIS_USERNAME: quarkus
      ARTEMIS_PASSWORD: quarkus
